# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [2]:
import numpy as np

In [11]:
# ejercicio 1
a = np.array([1, 2, 3, 4])
comparacion = (a != 0)

resultado = np.all(comparacion)

print(f"Arreglo: {a}")
print(f"Comparación (a != 0): {comparacion}")
print(f"Resultado (np.all(comparacion)): {resultado}")

Arreglo: [1 2 3 4]
Comparación (a != 0): [ True  True  True  True]
Resultado (np.all(comparacion)): True


In [12]:
# ejercicio 2
a = np.array([1, 2, 3, 4])
comparacion = (a != 0)

resultado = np.any(comparacion)

print(f"Arreglo: {a}")
print(f"Comparación (a != 0): {comparacion}")
print(f"Resultado (np.all(comparacion)): {resultado}")

Arreglo: [1 2 3 4]
Comparación (a != 0): [ True  True  True  True]
Resultado (np.all(comparacion)): True


In [13]:
# ejercicio 3
a = np.array([1, 2, np.nan, np.inf])
infinitos_check = np.isinf(a)
hay_infinitos = np.any(infinitos_check)

nan_check = np.isnan(a)
hay_nan = np.any(nan_check)

combinado_check = np.any(infinitos_check | nan_check)

print(f"Arreglo: {a}")
print(f"¿Contiene infinitos? (np.isinf): {infinitos_check}")
print(f"Resultado 'Hay Infinitos': {hay_infinitos}")
print("-" * 30)
print(f"¿Contiene NaN? (np.isnan): {nan_check}")
print(f"Resultado 'Hay NaN': {hay_nan}")
print("-" * 30)
print(f"¿Contiene valores infinitos O no numéricos?: {combinado_check}")

Arreglo: [ 1.  2. nan inf]
¿Contiene infinitos? (np.isinf): [False False False  True]
Resultado 'Hay Infinitos': True
------------------------------
¿Contiene NaN? (np.isnan): [False False  True False]
Resultado 'Hay NaN': True
------------------------------
¿Contiene valores infinitos O no numéricos?: True


In [14]:
# ejercicio 4
a = np.array([1, 2, np.inf])

es_infinito = np.isinf(a)

contiene_infinito = np.any(es_infinito)

print(f"Arreglo: {a}")
print(f"Verificación elemento a elemento (np.isinf): {es_infinito}")
print(f"Resultado final (np.any): {contiene_infinito}")

Arreglo: [ 1.  2. inf]
Verificación elemento a elemento (np.isinf): [False False  True]
Resultado final (np.any): True


In [15]:
# ejercicio 5
a = np.array([1, np.nan, 3])

es_nan = np.isnan(a)

contiene_nan = np.any(es_nan)

print(f"Arreglo: {a}")
print(f"Verificación elemento a elemento (np.isnan): {es_nan}")
print(f"Resultado final (np.any): {contiene_nan}")

Arreglo: [ 1. nan  3.]
Verificación elemento a elemento (np.isnan): [False  True False]
Resultado final (np.any): True


In [16]:
# ejercicio 6
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

mayor_que = a > b
mayor_o_igual_que = a >= b
menor_que = a < b
menor_o_igual_que = a <= b

print(f"Arreglo a: {a}")
print(f"Arreglo b: {b}")
print("-" * 40)
print(f"a > b (Mayor que):         {mayor_que}")
print(f"a >= b (Mayor o igual que):{mayor_o_igual_que}")
print(f"a < b (Menor que):         {menor_que}")
print(f"a <= b (Menor o igual que):{menor_o_igual_que}")

Arreglo a: [1 3 5]
Arreglo b: [2 3 4]
----------------------------------------
a > b (Mayor que):         [False False  True]
a >= b (Mayor o igual que):[False  True  True]
a < b (Menor que):         [ True False False]
a <= b (Menor o igual que):[ True  True False]


In [17]:
# ejercicio 7
a = np.array([1, 7, 13, 105])

num_elementos = a.size
bytes_por_elemento = a.itemsize
memoria_total = a.nbytes

print(f"Arreglo: {a}")
print(f"Tipo de datos de los elementos: {a.dtype}")
print("-" * 40)
print(f"Número de elementos (a.size): {num_elementos}")
print(f"Bytes por elemento (a.itemsize): {bytes_por_elemento} bytes")
print(f"Bytes totales ocupados (a.nbytes): {memoria_total} bytes")

# Verificación manual
print(f"Verificación manual (size * itemsize): {num_elementos * bytes_por_elemento} bytes")

Arreglo: [  1   7  13 105]
Tipo de datos de los elementos: int64
----------------------------------------
Número de elementos (a.size): 4
Bytes por elemento (a.itemsize): 8 bytes
Bytes totales ocupados (a.nbytes): 32 bytes
Verificación manual (size * itemsize): 32 bytes


In [18]:
# ejercicio 8
arreglos_de_ceros = np.zeros(10)

arreglos_de_unos = np.ones(10)

arreglos_de_cincos = np.full(10, 5)

print("1. Arreglo de 10 Ceros:")
print(arreglos_de_ceros)
print("-" * 30)
print("2. Arreglo de 10 Unos:")
print(arreglos_de_unos)
print("-" * 30)
print("3. Arreglo de 10 Cincos:")
print(arreglos_de_cincos)

1. Arreglo de 10 Ceros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------------------
2. Arreglo de 10 Unos:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
------------------------------
3. Arreglo de 10 Cincos:
[5 5 5 5 5 5 5 5 5 5]


In [19]:
# ejercicio 9
arreglo_secuencial = np.arange(30, 71)

print(f"Arreglo creado (desde 30 hasta 70):")
print(arreglo_secuencial)
print("-" * 40)
print(f"Primer elemento: {arreglo_secuencial[0]}")
print(f"Último elemento: {arreglo_secuencial[-1]}")

Arreglo creado (desde 30 hasta 70):
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
----------------------------------------
Primer elemento: 30
Último elemento: 70


In [20]:
# ejercicio 11
matriz_identidad = np.eye(3)

print("Matriz Identidad 3x3:")
print(matriz_identidad)

Matriz Identidad 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# ejercicio 12
numero_aleatorio = np.random.rand()

print(f"Número aleatorio entre 0 y 1: {numero_aleatorio}")

Número aleatorio entre 0 y 1: 0.4800844806814283


In [22]:
# ejercicio 13
arreglo_normal = np.random.randn(15)

print(f"Arreglo de 15 números con distribución Normal Estándar:")
print(arreglo_normal)
print("-" * 60)
print(f"Número de elementos: {arreglo_normal.size}")
print(f"Media aproximada: {np.mean(arreglo_normal):.4f}")
print(f"Desviación estándar aproximada: {np.std(arreglo_normal):.4f}")

Arreglo de 15 números con distribución Normal Estándar:
[-0.29921705  0.34916235 -0.07457213 -0.45336595  0.18871681  0.61946518
  0.47011949 -0.36376408  1.55936109  1.24522519  0.10627475  0.32638199
 -1.63963964 -0.11082381 -1.03403227]
------------------------------------------------------------
Número de elementos: 15
Media aproximada: 0.0593
Desviación estándar aproximada: 0.7751


In [27]:
# ejercicio 14
a = np.arange(15, 56)

valores_centrales = a[1:-1]

print(f"Arreglo completo (15 a 55):")
print(a)
print("-" * 60)
print(f"Valores excluyendo el primero y el último:")
print(valores_centrales)
print("-" * 60)
print(f"Primer valor original (excluido): {a[0]}")
print(f"Último valor original (excluido): {a[-1]}")

Arreglo completo (15 a 55):
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
------------------------------------------------------------
Valores excluyendo el primero y el último:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
------------------------------------------------------------
Primer valor original (excluido): 15
Último valor original (excluido): 55


In [28]:
# ejercicio 15
vector_equiespaciado = np.linspace(5, 50, 10)

print(f"Vector equitativamente distribuido (Longitud: 10):")
print(vector_equiespaciado)
print("-" * 60)
print(f"Primer elemento: {vector_equiespaciado[0]}")
print(f"Último elemento: {vector_equiespaciado[-1]}")
print(f"Número de elementos: {vector_equiespaciado.size}")

Vector equitativamente distribuido (Longitud: 10):
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
------------------------------------------------------------
Primer elemento: 5.0
Último elemento: 50.0
Número de elementos: 10


In [30]:
# ejercicio 16
vector = np.arange(21)

print(f"Vector original (0 a 20):")
print(vector)
print("-" * 60)

vector[9:16] = vector[9:16] * -1

print(f"Vector modificado (Valores de 9 a 15 con signo cambiado):")
print(vector)

Vector original (0 a 20):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
------------------------------------------------------------
Vector modificado (Valores de 9 a 15 con signo cambiado):
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [31]:
# ejercicio 17
a = np.array([1, 2, 3])

lista_python = a.tolist()

print(f"Arreglo original (Tipo: {type(a)}): {a}")
print("-" * 50)
print(f"Lista convertida (Tipo: {type(lista_python)}): {lista_python}")

Arreglo original (Tipo: <class 'numpy.ndarray'>): [1 2 3]
--------------------------------------------------
Lista convertida (Tipo: <class 'list'>): [1, 2, 3]


In [32]:
# ejercicio 18
l = [1, 2, 3]

arreglo_numpy = np.array(l)

print(f"Lista original (Tipo: {type(l)}): {l}")
print("-" * 50)
print(f"Arreglo convertido (Tipo: {type(arreglo_numpy)}): {arreglo_numpy}")

Lista original (Tipo: <class 'list'>): [1, 2, 3]
--------------------------------------------------
Arreglo convertido (Tipo: <class 'numpy.ndarray'>): [1 2 3]


In [35]:
# ejercicio 10
numeros_pares = np.arange(30, 71, 2)

print(f"Arreglo de números pares entre 30 y 70:")
print(numeros_pares)
print("-" * 60)
print(f"Primer elemento: {numeros_pares[0]}")
print(f"Último elemento: {numeros_pares[-1]}")

Arreglo de números pares entre 30 y 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
------------------------------------------------------------
Primer elemento: 30
Último elemento: 70


In [33]:
# ejercicio 19
m = np.array([[1, 2],
              [3, 4]])

matriz_par_check = (m % 2) == 0

print(f"Matriz original:")
print(m)
print("-" * 30)
print(f"Resultado (Matriz Booleana de Pares):")
print(matriz_par_check)

Matriz original:
[[1 2]
 [3 4]]
------------------------------
Resultado (Matriz Booleana de Pares):
[[False  True]
 [False  True]]


In [34]:
# ejercicio 20
m = np.array([[1, 2, 3],
              [4, 5, 6]])

dimensiones = m.shape

num_filas = dimensiones[0]
num_columnas = dimensiones[1]

print(f"Matriz m:")
print(m)
print("-" * 30)
print(f"Dimensiones de la matriz (m.shape): {dimensiones}")
print(f"Número de filas: {num_filas}")
print(f"Número de columnas: {num_columnas}")

Matriz m:
[[1 2 3]
 [4 5 6]]
------------------------------
Dimensiones de la matriz (m.shape): (2, 3)
Número de filas: 2
Número de columnas: 3
